name: Re-generate list
on:
  - push
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Generate
        run: |
          make all
      - name: run test push
        run: |
          git config --global user.name 'driazati'
          git config --global user.email 'driazati@users.noreply.github.com'
          git commit -am "[gha] automated re-genenerate"
          git push
